### PR TITLE
GameType Forge 1.12X Lower

### PR DESCRIPTION
**Pull request by MinePlay85**
Sorry I close the recent pull request 
Now the new.
Bye.

### CODE REVIEW

**Comment by FlowArg** [comment]
I don't see the point of this `GameType`. This behavior is already reproducible through a `GameType.V1_8_HIGHER` plus a `GameTweak.FORGE`.

**Comment by MinePlay85** [comment]
I know but with V1_8_HIGHER we don't start the client with Forge

**Comment by FlowArg** [comment]
The problem come from your code, not from the lib. Come on the Discord we'll help you.

**Comment by MinePlay85** [comment]
Can you give me the link ?

**Comment by FlowArg** [comment]
https://discord.gg/yvv78kV

**Pull request closed without merging**
